---
engines:
  brakeman:
    enabled: true
    checks:
      csrf_protection_missing:
        enabled: false
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/LineLength:
        enabled: false
      Rubocop/Style/StringLiterals:
        enabled: false
      Rubocop/Style/Documentation:
        enabled: false
      Rubocop/Style/StringLiteralsInInterpolation:
        enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- app/assets/*
- vendor/assets/*
- public/assets/*
- spec/*
- features/*
- lib/*
- config/environments/*
- db/schema.rb
- Gemfile.lock
- db/migrate
