default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  database: c9
  adapter: mysql2
  username: root
  password:

test: &test
  <<: *default
  database: test

production:
  <<: *default
  database: production
